### ISSUE TITLE
Grabbing a window throws exception when its the only tab

### ISSUE THREAD

**Issue by vepukki** [sskodje/wpfchrometabs-mvvm#1]
A first chance exception of type 'System.InvalidOperationException' occurred in PresentationFramework.dll
The program '[5796] Demo.vshost.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

This exception is thrown when there are two tabs open and you drag the other one to new window and then close the remaining tab and drag the window back to the TabControl (to grab it as a tab again).

**Comment by vepukki** [comment]
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=Can only call DragMove when primary mouse button is down.
  Source=PresentationFramework
  StackTrace:
       at System.Windows.Window.DragMove()
       at ChromeTabs.ChromeTabPanel.StartTabDrag(Point p, ChromeTabItem tab, Boolean isTabGrab)
       at ChromeTabs.ChromeTabPanel.StartTabDrag(ChromeTabItem tab, Boolean isTabGrab)
       at ChromeTabs.ChromeTabControl.GrabTab(Object viewModel)

This was the cause and when I catch this exception in my application then it works:

try
{
     this.MyTabControl.GrabTab(dockedWindowVM);
}
catch(InvalidOperationException except)
{ 
     Debug.WriteLine("Grabbing failed"); // do nothing
}

**Comment by sskodje** [comment]
I reopened this, because it really is a bug :)
What happens is a combination of having "drag window with one tab" enabled, and dragging in a window to an empty tab bar. Then it tries to drag the window, but the user does not have the primary button down on the window, hence the exception.

I will upload a fix later today.

**Comment by vepukki** [comment]
In my case I didn't have the DragWindowWithOneTab="True" set on my tab control, but I it still gave the exception.

**Comment by sskodje** [comment]
Alright, the issue should be fixed now. Closing this.
