### ISSUE TITLE
Window dragging, drags a new Tab after adding

### ISSUE THREAD

**Issue by Revsol** [sskodje/wpfchrometabs-mvvm#11]
If you have only one Tab, you can move the whole Window with that tab, but if you add a new Tab after the dragging, you drag that new Tab directly after adding. It's reproduceable in the Demo.

**Comment by sskodje** [comment]
It was a variable that was not set to null like it should when dragging the window. I updated the source with the fix.

**Comment by Revsol** [comment]
Great, thx. When do you upload it to NuGet?

**Comment by sskodje** [comment]
It should be updated on nuget now

**Comment by Revsol** [comment]
Works like a charm ;)
