### ISSUE TITLE
Layout breaks when MinimumTabWidth ot MaximumTabWidth is set high

### ISSUE THREAD

**Issue by Revsol** [sskodje/wpfchrometabs-mvvm#12]
When you set the MinimumTabWidth or the MaximumTabWidth to a high Value like 300 the tabs will become ugly. Tested in the Demo.
![brokenlayout](https://cloud.githubusercontent.com/assets/16817022/12577411/7160eec4-c41a-11e5-8516-7ab11c90d722.jpg)

**Comment by sskodje** [comment]
The problem is a static value in the tab item theme.

                <ControlTemplate TargetType="{x:Type local:ChromeTabItem}">
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="0.1*" /> //used to be 5
                            <ColumnDefinition Width="*" />
                            <ColumnDefinition Width="Auto" />
                            <ColumnDefinition Width="0.1*" /> // used to be 5
                        </Grid.ColumnDefinitions>

I updated the source with the changes.

**Comment by Revsol** [comment]
Thx ;)
I tested it in the Demo and unfortunately it still looks not good. The TabImage and CloseButton are now in the Tab, but the Tab itself stretches so much that it becomes flat. The Angles of the Trapezoid changes and i guess they shouldn't

**Comment by sskodje** [comment]
Unfortunately there is no way to selectively stretch a path. It's only a problem with unrealisticly large tabs imo.

**Comment by sskodje** [comment]
I managed to get it working using a custom shape class. This issue is fixed with v1.2.3.

**Comment by Revsol** [comment]
It looks a lot better now, Thx.
But.... ;)
if you resize the window fast, you get weirded behavior
![brokenlayout2](https://cloud.githubusercontent.com/assets/16817022/12619454/63c81356-c518-11e5-8699-09ab94fe9fff.jpg)

**Comment by sskodje** [comment]
Note to self: Don't use "ActualSize" inside layout passes.

Fixed in 1.2.4.

**Comment by Revsol** [comment]
Looks good, Thank you very much ;)
