### ISSUE TITLE
Shape.Fill

### ISSUE THREAD

**Issue by phleb3** [sskodje/wpfchrometabs-mvvm#15]
This xaml command is not found on my system

**Comment by sskodje** [comment]
It should be a part of the standard System.Windows.Shapes [namespace.](https://msdn.microsoft.com/en-us/library/system.windows.shapes.shape.fill(v=vs.110).aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-1) in presentationframework.dll. It should be there by default in a new wpf project.

**Comment by phleb3** [comment]
thanks, I found my problem. Thanks for the great projec
