### ISSUE TITLE
Tabs still dragable

### ISSUE THREAD

**Issue by JranZu** [sskodje/wpfchrometabs-mvvm#17]
If you select a tab and in so doing the tabs move up or down so the mouse is not longer over said tab - then when you move the mouse back over the tab it still moves around until you press and release the mouse button.

**Comment by sskodje** [comment]
Thanks for reporting. I'll check it out.

**Comment by sskodje** [comment]
Commit bb88e6fc2a824ed3de99ec9d4126885eb48c5b2c closes #17
