### ISSUE TITLE
Able to see a preview of the unselected tab when you mouseover on the Tab

### ISSUE THREAD

**Issue by ancgate** [sskodje/wpfchrometabs-mvvm#18]
This is not an issue, but a feature I am working on and I think it will be very interesting. The idea is for me to be able to view a snapshot like the on the picture below. Can you point me in the right direction? Thanks

![tabpreview](https://user-images.githubusercontent.com/4063982/37178486-a10e5b16-22f0-11e8-9da1-7f2552da8406.png)

**Comment by sskodje** [comment]
Interesting problem indeed!

To generate a snapshot, you could use [RenderTargetBitmap](https://msdn.microsoft.com/en-us/library/system.windows.media.imaging.rendertargetbitmap.render(v=vs.110).aspx) to snapshot your tab content and display it in an Image control.

Now here comes the interesting bit. If it's your currently loaded tab, you could simply get the current content of the tab control by walking the visual tree and input it into the rendertargetbitmap. If it's any other tab, it's most likely not loaded, and all you have to go by is the ViewModel. This means that you need to create the content, measure, arrange and apply the layout without actually putting it into your UI, then snapshot it!

Luckily it's fully possible to render a control without displaying it. This means you can do something like this: 

        private void TabHeader_MouseEnter(object sender, MouseEventArgs e)
        {
            FrameworkElement header = (FrameworkElement)((FrameworkElement)sender).TemplatedParent;
            var vm = header.DataContext;
            if(vm is MyViewModel)
            {
                Border border = new Border();
                border.BorderThickness = new Thickness(2);
                border.BorderBrush = new SolidColorBrush(Colors.Black);

                //..or whatever your content may be.
                MyUserControl control = new MyUserControl();
                control.DataContext = vm;
                control.Background = new SolidColorBrush(Colors.White);
                border.Child = control;

               //These 3 lines does the magic of laying out our control so we can render it into the RenderTargetBitmap
                border.Measure(new Size(this.ActualWidth, this.ActualHeight));
                border.Arrange(new Rect(new Size(this.ActualWidth, this.ActualHeight)));
                border.UpdateLayout(); 

                RenderTargetBitmap rtb = new RenderTargetBitmap((int)border.ActualWidth, (int)border.ActualHeight, 96d, 96d , System.Windows.Media.PixelFormats.Default);
                rtb.Render(border);
                
                Image img = new Image();
                img.Source = rtb;
                img.Width = 300;
                img.Stretch = Stretch.Uniform;

                Popup popup = new Popup();
                popup.Child = box;
                popup.PlacementTarget = header;
                popup.Placement = PlacementMode.Bottom;
                popup.IsOpen = true;
                popup.StaysOpen = false;
            }

This event is then fired from the content in the tab controls ItemTemplate. Of course this is a very crude example, but i think it should be a working.

**Comment by ancgate** [comment]
Thanks. I will use it. But I have a question what is box in popup.Child = box;

**Comment by sskodje** [comment]
Oh, a typo. It should be "img". I fixed it.

**Comment by ancgate** [comment]
Thanks, I will try it and let you now.

**Comment by ancgate** [comment]
It is working.

        private void TabHeader_MouseEnter(object sender, MouseEventArgs e)
        {
            FrameworkElement header = (FrameworkElement)sender;
            var vm = header.DataContext;
            if (vm is TabBase)
            {
                Border border = new Border();
                border.BorderThickness = new Thickness(2);
                border.BorderBrush = new SolidColorBrush(Colors.Black);

                //..or whatever your content may be.
                UserControl2 control = new UserControl2();
                control.DataContext = vm;
                //RenderTargetBitmap does not work with transparent backgrounds, so if it is, it must be set to a color.
                control.Background = new SolidColorBrush(Colors.White);
                border.Child = control;

                //These 3 lines does the magic of laying out our control so we can render it into the RenderTargetBitmap
                border.Measure(new Size(this.ActualWidth, this.ActualHeight));
                border.Arrange(new Rect(new Size(this.ActualWidth, this.ActualHeight)));
                border.UpdateLayout();

                RenderTargetBitmap rtb = new RenderTargetBitmap((int)border.ActualWidth, (int)border.ActualHeight, 96d, 96d, System.Windows.Media.PixelFormats.Default);
                rtb.Render(border);

                Image img = new Image();
                img.Source = rtb;
                img.Width = 300;
                img.Stretch = Stretch.Uniform;

                Popup popup = new Popup();
                popup.Child = img;
                popup.PlacementTarget = header;
                popup.Placement = PlacementMode.Bottom;
                popup.IsOpen = true;
                popup.StaysOpen = false;
                
            }


        }


Now I will to put it in the library and also, 
1) when the mouse leave, and goes to another tab, current popup must be closed and snapshot the other one
2) When the mouse leave and doesn't go the another tab, current pop also must be close.

**Comment by sskodje** [comment]
Yeah this was just a crude example. You need to create or find code to get "mouse hover" feature, as it isn't built in. Also the popup needs to be made a property in your class so you can close and reuse it when hoverin other tabs or when the mouse leaves the tab. You most likely also need to create the thumbs async, and cache the results. Good luck :)

**Comment by sskodje** [comment]
I also just released a new version, where i exposed a method for getting the content presenters for any cached tabs, if using the persistent tab feature. See ce6a71551a9fd1b2d31b3ab5b2fd242cdc70a199. You can use this content presenter to get a snapshot of already loaded tabs.

**Comment by ancgate** [comment]
Thank you very much, I really appreciate your help. Once I made it work, I will commit the code and push it to your repository if you don't find any inconvenient.
