### ISSUE TITLE
CloseTabCommand CanExecute

### ISSUE THREAD

**Issue by marinkobabic** [sskodje/wpfchrometabs-mvvm#20]
CloseTabCommand the canExecute is actually ignored. There is now way to prevent the user from closing the last tab using MVVM

**Comment by sskodje** [comment]
So they are. I'll push a fix soon!

**Comment by marinkobabic** [comment]
Many thanks.

**Comment by sskodje** [comment]
Fixed with commit 2781c538c293f36da12290fddaa5d2166fe38fd9
