### ISSUE TITLE
Issue with snapping window back into tabs (Windows 10).

### ISSUE THREAD

**Issue by Sugz** [sskodje/wpfchrometabs-mvvm#21]
I'm trying this on Windows 10, and the ability to snap a window back into tabs doesn't seem to work.
Here is a quick [example](https://screencast-o-matic.com/watch/cFilIrFAqp)
Otherwise, this seems quite nice :)

**Comment by frankengelbrecht** [comment]
Guten Tag und vielen Dank für ihre Nachricht.

Leider ist mein Büro vom 09.07.2018 bis einschliesslich 12.07.2018 nicht besetzt, danach stehe ich gerne wieder zu ihrer Verfügung.

Mfg,
Frank Engelbrecht

**Comment by sskodje** [comment]
The problem is an issue with "UI debugging tools", which i'm assuming puts an overlay over the window that stops mouse events etc from working. I don't have a fix apart from disabling the UI debugging tools.
