### ISSUE TITLE
Close tab with middle mouse button

### ISSUE THREAD

**Issue by pp111** [sskodje/wpfchrometabs-mvvm#23]
Is it possible to close a tab by pressing the middle mouse button like in Chrome? 

My application is not receiving the close command when I press the middle button.

**Comment by sskodje** [comment]
I just tested it, and it worked fine this way, based on the demo project:


     (...)
          <ct:ChromeTabControl.ItemTemplate>
                <DataTemplate>
                    <Grid MouseUp="Grid_MouseUp">
                     (...)


and then

       private void Grid_MouseUp(object sender, MouseButtonEventArgs e)
        {
           if( e.ChangedButton== MouseButton.Middle)
            {
                ViewModelExampleBase vm = (ViewModelExampleBase)DataContext;
                vm.CloseTabCommand.Execute(((FrameworkElement)sender).DataContext);
            }
        }

**Comment by pp111** [comment]
Thank you !
