### ISSUE TITLE
ChromeTabs DLL is not Signed with a Strong Name Key

### ISSUE THREAD

**Issue by IvanGit** [sskodje/wpfchrometabs-mvvm#27]
Hello,

I use ChromeTabs from NuGet in my application. Because my application is signed I get the error while ChromeTabs dll loading:

Could not load file or assembly 'ChromeTabs, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Could you sign the assembly in NuGet package? Thank you.

**Comment by sskodje** [comment]
Sure. I've updated on NuGet.
