### ISSUE TITLE
Sometimes an exception is thrown when clicking on a tab.

### ISSUE THREAD

**Issue by stebla27** [sskodje/wpfchrometabs-mvvm#29]
Sometime the chrome tab throws an out of bounds exception when clicking on a tab:
"   at System.Windows.Controls.ItemCollection.GetItemAt(Int32 index)\r\n   at ChromeTabs.ChromeTabControl.MoveTab(Int32 fromIndex, Int32 toIndex)\r\n   at ChromeTabs.ChromeTabPanel.<>c__DisplayClass57_0.<OnTabRelease>g__completed|0()\r\n   at System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)\r\n   at System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()\r\n   at System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()\r\n   at System.Windows.Media.Animation.TimeManager.Tick()\r\n   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)\r\n   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"

I'm not sure but maybe it can be fixed by doing more checks in MoveTab.
Current code:
 if (Items.Count == 0 || fromIndex == toIndex || fromIndex >= Items.Count)
            {
                return;
            }
            object fromTab = Items[fromIndex]; //fromIndex could be < 0
            object toTab = Items[toIndex]; //toIndex could be < 0 and outside of array!

Better:
 if (fromIndex == toIndex || fromIndex >= Items.Count || toIndex >= Items.Count || toIndex < 0 || fromIndex < 0)
 {
                return;
 }

But I'm not sure if it fixes the bug. The question is why is a invalid index passed to the function and why is MoveTab called if I click on a tab page and release the mouse button. This should not trigger a MoveTab operation.

**Comment by sskodje** [comment]
Are you sure you are experiencing toIndex to be < 0? There is only [one place](https://github.com/sskodje/wpfchrometabs-mvvm/blob/9185e5175b88fc85a82e22eb06063a8a61ef93e5/ChromeTabs/ChromeTabPanel.cs#L578) that calls MoveTab, and it has a check to disallow values below 0.

**Comment by stebla27** [comment]
I'm not sure if toIndex is < 0! I only see that out of bounds exception!
The only index access is with fromIndex and toIndex. fromIndex is checked in code, toIndex not.
This is why I suppose that toIndex is < 0 or >= Items.Count.
Maybe sometimes a drag operation is started when moving the mouse 1px while clicking.
The exception happens on mouse release.
The only thing I can say is that it sometimes happens, when I click a tab page.

**Comment by sskodje** [comment]
It may be possible that it can be above the valid index range, i'll do some testing.

**Comment by sskodje** [comment]
I managed to reproduce it by programatically closing the tab while dragging it, and i suspect something similar must happen to you. I added checks to prevent this as you suggested.

Fixed with 08a618ec9e86a59112b31f0d9498ec39ecd1fe7b
