### ISSUE TITLE
Is it possible to place the tab headers strip at bottom?

### ISSUE THREAD

**Issue by ppradeepk** [sskodje/wpfchrometabs-mvvm#3]
Similar to WPF TabControl, is it possible to change the trabstrip placement to Bottom from the standard top location?

**Comment by sskodje** [comment]
Yes, it's pretty simple using the control template. To use the one from the demo project as an example, you can make the change like this: 

                <ControlTemplate TargetType="{x:Type ct:ChromeTabControl}">
                    <Grid>
                        <Grid.RowDefinitions>
                            <RowDefinition Height="*" />//<-------Change rows so the top row fills the space
                            <RowDefinition Height="30" /> 
                        </Grid.RowDefinitions>
                        <Border Background="{TemplateBinding Background}"
                                BorderThickness="0,0,0,1"
                                BorderBrush="#FF999999"
                                Grid.Row="1"//<-------move the container hosting the ChromeTabPanel to row 1
                                Padding="10,5,10,0">
                            <ct:ChromeTabPanel IsItemsHost="True"
                                               Background="AliceBlue" />
                        </Border>
                        <Grid Grid.Row="0">//<-------move the container hosting the content to row 0
                            <Border Background="WhiteSmoke">
                                <ContentPresenter Content="{TemplateBinding SelectedContent}" />
                            </Border>
                        </Grid>
                    </Grid>
                </ControlTemplate>

**Comment by ppradeepk** [comment]
Thanks! i made this very change in control template.
