### ISSUE TITLE
Preserve tab content when tearing tab to a new window

### ISSUE THREAD

**Issue by frankdekker** [sskodje/wpfchrometabs-mvvm#30]
Hi. I've tab contents with a webview2. The url of the webview2 is bound to a viewmodel. Now when i tear out a tab only the viewmodel is passed along. If a new user control is initialized for that viewmodel, the browser will just create a new instance and load that url, losing the current navigation state. I've looked through the examples and source in depth, but I'm unable to find a solution.

My reasoning so far:
- tearing away a tab should also pass the ChromeTabItem instance via TabDragEventArgs.
- get the UIElement from the ChromeTabItem control.
- transfer the UIElement to the new window.

As i'm quite stuck at the moment, any tips would be highly appreciated.

**Comment by sskodje** [comment]
Usually with MVVM you are supposed to persist the data in the viewmodel and recreate the control, but as you say, unfortunately you can't do that with things like WebView. 

You are on the right track, but a ChromeTabItem is the control for a tab header, not the content of the tab itself. The TabControl actually do not know about the tab content, apart from the ViewModel, and a ContentPresenter that loads the DataTemplate for the tab contents that you defined in your XAML.

What i think you instead need to do is snatch the WebView2 out from your control that hosts the WebView in its Unloaded event and store it somewhere practical. Then in the Loaded event of your control in the new window, you must check if there is a saved WebView waiting, and then inject it into your control. The same way, when docking the window to the tab control again, you must take the WebView from the window control, store it, and inject it into the tabbed control. 

You can probably store some state in your ViewModel to make this easier.

Good luck  :)

**Comment by frankdekker** [comment]
Thanks, that helps a lot. I'll try to save+load of the WebView. Thanks for the quick reply.
