### ISSUE TITLE
How to place a "+” as caption in the AddButton?

### ISSUE THREAD

**Issue by SwaroopSomanna** [sskodje/wpfchrometabs-mvvm#31]
Is there any way to add text (caption) to the AddButton (Add tab button)?
I want to place a "+” symbol on the AddButton. So that the user knows they can open a new tab by clicking on that button.
Thank you.

**Comment by sskodje** [comment]
Check out the CustomStyleExampleWindow in the demo project, it has an example of how to change the template of the "add tab" button.
