### ISSUE TITLE
Buttons are disabled after closing Tab pressed

### ISSUE THREAD

**Issue by Hank2014** [sskodje/wpfchrometabs-mvvm#34]
Inside a TabItem there is a button, originally enabled, and when pressed a message box is shown.
![image](https://user-images.githubusercontent.com/8908682/116811947-54975480-ab4c-11eb-918f-358374c9d18a.png)

The ChromeTabControl is defined in my MainWindow and the Button is defined in UserControl1, which serves as the view of TabItem. Notice that the CloseCommand of ChromeTabControl left undefined on purpose.
```
<Window x:Class="playground.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:ct="clr-namespace:ChromeTabs;assembly=ChromeTabs"
        xmlns:local="clr-namespace:playground"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Window.Resources>
        <DataTemplate DataType="{x:Type local:CustomizedTabClass}">
            <local:UserControl1/>
        </DataTemplate>
    </Window.Resources>

    <DockPanel LastChildFill="True">
        <TextBlock DockPanel.Dock="Top" Text="fixed"/>
        <Grid DockPanel.Dock="Bottom" Margin="5">

            <ct:ChromeTabControl x:Name="MainTabControl"
                                ItemsSource="{Binding ItemCollection}"
                                SelectedItem="{Binding SelectedTab}"
                                TabPersistBehavior="All">

            </ct:ChromeTabControl>

        </Grid>
    </DockPanel>
</Window>

```

**If I press "close" (as the black rectangle indicates), of course the tab will not be closed, but why is the button disabled?**

![image](https://user-images.githubusercontent.com/8908682/116812043-d8e9d780-ab4c-11eb-9da0-5152c88c8383.png)

**Comment by Hank2014** [comment]
Side Note) By CloseCommand I mean CloseTabCommand.

**Comment by sskodje** [comment]
It's hard to guess why this happens without knowing the code of your control, but if your button is bound to a command, most likely the binding is updated when you press the button, and the "CanExecute" of the command is triggered and returns false.
