### ISSUE TITLE
I want to add a function

### ISSUE THREAD

**Issue by mzy666888** [sskodje/wpfchrometabs-mvvm#35]
I want to Add Command: CloseAllExcludingPinnedTabsCommand

if tabitem is pinned, execute CloseAllTabCommand ,don't close the pinned tabitems

**Comment by sskodje** [comment]
Tabs are removed when you remove the models from your collection. So create a menu item on the tab like shown in the demo app, and when you call it, remove all models from your collection that is not pinned.
