### ISSUE TITLE
Unable to change the size of the add tab button.

### ISSUE THREAD

**Issue by frankdekker** [sskodje/wpfchrometabs-mvvm#38]
Currently it is possible to custom style the add tab button, but the size is hardcoded to `new Size(20, 12)`. Line 111 in `ChromeTabPanel.cs`. 

I added properties  `AddButtonWidth` and `AddButtonHeight` to `ChromeTabControl.cs`, but my skills are kinda lacking to get this to work inside the `ChromeTabPanel.cs`. 

You have some pointers how to update the `_addButtonSize` property inside `ChromeTabPanel.cs` when the width or height is set from xaml?

**Comment by sskodje** [comment]
I'm sorry it took a while to respond, i merged in your changes now 👍
