### ISSUE TITLE
Why it always crash in Windows XP SP3

### ISSUE THREAD

**Issue by VanLzx** [sskodje/wpfchrometabs-mvvm#4]
i found if remove the code in "Generic.xaml" file it can run,

<Style TargetType="{x:Type local:ChromeTabControl}">
....
   
....
</Style>

but i can't remove it.Hope somebody help me,please~

**Comment by sskodje** [comment]
By removing the content presenter you won't load whatever is inside the controls datatemplate, so that's probably where the problem is. Can you post some exception details from a crash?

**Comment by VanLzx** [comment]
Thanks for your reply.

Sorry,there's not any exception,i comfirmed by debug many times.Even i added an Button(Code like behind), it did not work....

object itemToAdd = new ChromeTabItem
{
	Content = new Button{Text="Test"},
};
this.chrometabs.AddTab(itemToAdd, true);

Today, i found some other Windows XP SP3 computer can run it,i do not know why.

**Comment by sskodje** [comment]
If it's specific to a computer, maybe you can try check if your .NET installation  is up to date on the computer.

I'm sorry i can't help you more than that. It doesn't look like the crash is caused by this control.

**Comment by VanLzx** [comment]
thx,i will try.

think you again😁

Date: Wed, 21 Oct 2015 06:46:36 -0700
