### ISSUE TITLE
Not able to change tab background color 

### ISSUE THREAD

**Issue by AnkurRaval** [sskodje/wpfchrometabs-mvvm#40]
I'm trying to apply dark theme in my WPF application. The tabs are not taking the theme color. Can you show me a way how that can be done?

**Comment by sskodje** [comment]
You must create a new style for your tabs and reference it as ItemContainerStyle on the ChromeTabControl, as the tab backgrounds unfortunately is hardcoded in the default style.

The easiest is probably to just copy the [default style](https://github.com/sskodje/wpfchrometabs-mvvm/blob/9d46b5275f50695e296be82729ebc544689833c1/ChromeTabs/Themes/Generic.xaml#L128) and do your changes, then reference is like this:

`<ct:ChromeTabControl 
                              ItemContainerStyle="{StaticResource MyStyle}">`
