### ISSUE TITLE
dont show usercontrol at start

### ISSUE THREAD

**Issue by tenjor** [sskodje/wpfchrometabs-mvvm#5]
The first window does not load the usercontrol at start, but after you switch between tabs it loads correctly.

**Comment by sskodje** [comment]
You are absolutely correct. There was a bug where the tab content would not be set if the SelectedItem property were assigned before the tab items had finished loading in the control. 

Thanks a lot for notifying me!

**Comment by sskodje** [comment]
Fixed in 1.1.1
