### ISSUE TITLE
Tabstrip Placement

### ISSUE THREAD

**Issue by hpposch** [sskodje/wpfchrometabs-mvvm#6]
Hi,
i am using chromeTabs and i really like it.
The only thing i am missing is the TabStripPlacement Property.
https://msdn.microsoft.com/en-us/library/system.windows.controls.tabcontrol.tabstripplacement(v=vs.110).aspx

I want to place the TabPanel on the left side of my control.
Is there any way to do this?

**Comment by sskodje** [comment]
I'm sorry, but that functionality is not supported in this control, as it would require a redesign and a lot of work. The chrome tabs are made to overlap horizontally, not vertically.
