### ISSUE TITLE
Persisted VisualTree

### ISSUE THREAD

**Issue by Revsol** [sskodje/wpfchrometabs-mvvm#7]
I really like this TabControl, but is there a way to persist the VisualTree of the Tabs?
If i switch a Tab the VisualTree will be new generated and it loses all of its sorting settings.

The Problem is really good described here: http://www.codeproject.com/Articles/212233/Persist-the-Visual-Tree-when-switching-tabs-in-the
You can also take a look on Sascha Barbers Comment and his solution: http://www.codeproject.com/Articles/212233/Persist-the-Visual-Tree-when-switching-tabs-in-the?fid=1633690&df=10000&mpp=50&prof=False&sort=Position&view=Thread&spc=Relaxed&select=4702925#xx4702925xx

**Comment by sskodje** [comment]
I'll take a look!

**Comment by sskodje** [comment]
This issue is fixed in version 1.2

**Comment by Revsol** [comment]
Thank you very much.
But i found a small Bug. I can't reproduce it in you Demo, only in my Application.
If if remove a tab from my ObservableCollection i get an NullReferenceException:

   bei ChromeTabs.ChromeTabItem.OnIsSelectedChanged(DependencyObject d, DependencyPropertyChangedEventArgs args) in c:\_Downloads\Iseckec\Downloads\wpfchrometabs-mvvm-master (1)\wpfchrometabs-mvvm-master\ChromeTabs\ChromeTabItem.cs:Zeile 154.
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.ClearValueCommon(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata)
   bei System.Windows.DependencyObject.ClearValue(DependencyProperty dp)
   bei System.Windows.Controls.Primitives.Selector.ClearContainerForItemOverride(DependencyObject element, Object item)
   bei System.Windows.Controls.ItemsControl.MS.Internal.Controls.IGeneratorHost.ClearContainerForItem(DependencyObject container, Object item)
   bei System.Windows.Controls.ItemContainerGenerator.UnlinkContainerFromItem(DependencyObject container, Object item, IGeneratorHost host)
   bei System.Windows.Controls.ItemContainerGenerator.OnItemRemoved(Object item, Int32 itemIndex)
   bei System.Windows.Controls.ItemContainerGenerator.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   bei System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   bei System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   bei System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   bei System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   bei System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   bei System.Windows.Controls.ItemCollection.OnViewCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   bei System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   bei System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   bei System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   bei System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   bei System.Windows.Data.ListCollectionView.ProcessCollectionChangedWithAdjustedIndex(NotifyCollectionChangedEventArgs args, Int32 adjustedOldIndex, Int32 adjustedNewIndex)
   bei System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   bei System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   bei System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   bei System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)
   bei System.Collections.ObjectModel.Collection`1.Remove(T item)
   bei CoFr.Client.Mvvm.TabApplication.ApplicationViewModel.CloseTab(TabViewModel tab) in C:\Projects\CoFr\app\CoFr.Client.Mvvm.TabApplication\ApplicationViewModel.cs:Zeile 100.
   bei CoFr.Client.Mvvm.RelayCommand`1.Execute(Object parameter) in C:\Projects\CoFr\app\CoFr.Client.Mvvm\RelayCommand.cs:Zeile 72.
   bei ChromeTabs.ChromeTabControl.RemoveTab(Object tab) in c:\_Downloads\Iseckec\Downloads\wpfchrometabs-mvvm-master (1)\wpfchrometabs-mvvm-master\ChromeTabs\ChromeTabControl.cs:Zeile 492.
   bei ChromeTabs.ChromeTabItem.HandleCloseTabCommand(Object sender, ExecutedRoutedEventArgs e) in c:\_Downl...ject target)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   bei System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   bei System.Windows.Input.RoutedCommand.ExecuteCore(Object parameter, IInputElement target, Boolean userInitiated)
   bei MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   bei System.Windows.Controls.Primitives.ButtonBase.OnClick()
   bei System.Windows.Controls.Button.OnClick()
   bei System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   bei System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Window.ShowHelper(Object booleanBox)
   bei System.Windows.Window.Show()
   bei System.Windows.Window.ShowDialog()

The Problem is that tabItem.ParentTabControl is Null in ChromeTabItem.OnIsSelectedChanged.
i have a small workaround but i don't think that is the best solution. i changed the "if" to:
```C#
tabItem.ParentTabControl != null && tabItem.ParentTabControl.TabPersistBehavior == TabPersistBehavior.Timed
```

**Comment by sskodje** [comment]
Does it happen every time you remove a tab? It's weird, since the tab items should not be able to live without a parent tab control.

**Comment by Revsol** [comment]
Yes, it happens every time. My CloseTabCommand removes the Tab from my ObservableCollection:
```C#
Tabs.Remove(tab);
```

**Comment by Revsol** [comment]
My Tabs can contain different views in a list and behave like a BrowserTab where you can GoBack to previous Views. The "Part_ItemsHolder" Grid ignores the setting of the DataContext to my "SelectedTab.CurrentView", so i added a new View that got selected if Part_ItemsHolder contains a TabViewModel and in this view added a ContentPresenter to my CurrentView.
Maybe is this the Problem.

**Comment by sskodje** [comment]
Can you explain more about your issue with Part_ItemsHolder? Perhaps we can just fix the root cause of this.

**Comment by Revsol** [comment]
i have the Part_ItemsHolder implemented like in your Demo:
```C#
<Grid x:Name="PART_ItemsHolder" Grid.Row="1" />
```
i have removed the VisibilityConverter from the Template, because i saw no really use of it.
But thats not the Problem, the Exception will be thrown with and without the Converter.
I also removed the:
```C#
 <Grid Grid.Row="1"
    Visibility="{TemplateBinding TabPersistBehavior,Converter={StaticResource TabPersistBehaviorToContentPresenterVisibilityConverter}}">
                            <ContentPresenter Content="{TemplateBinding SelectedContent}" />
</Grid>
```
Because there seemed not a really use of it. (Please correct me, if i'm wrong)

I have an ApplicationViewModel, this contains an ObservableCollection of TabViewModels(Tabs). And each TabViewModel has a ObservableCollection of ContentView(Views). A ContentView is a complete View that should be shown in the Tab. The Reason for this is to GoBack and GoForward like a real Browser.

I told the TabControl to Bind:
```C#
ItemsSource="{Binding Tabs}"
SelectedContent="{Binding SelectedTab, Mode=OneWayToSource}"
```

The Problem now is that the Part_ItemsHolder Grid now contains the SelectedTab that is an TabViewModel. But the Content should be the CurrentView from the SelectedTab.
When i set the Content or the DataContext of the Grid, it is complete ignored and the ContentSelector tries to find a View for TabViewModel.
So i created a View for the TabViewModel that the ContentSelector can show this View and in this View i added
```C#
<ContentPresenter Content="{Binding CurrentView}" />
```

This works fine. That is not a real Issue for me, cause i really need this TabView for StandardCommands. But maybe its the reason for the NullReferenceException.

I hope i could explain my Problem ;)

**Comment by sskodje** [comment]
When you say that each tab has a collection of views, is that a collection of literal views, like a control, page or window? Because it's not good practice to keep references to views inside a viewmodel.

The Part_ItemsHolder will contain the ViewModel for your tab yes. And it will load a user control that corresponds, as per reference to the demo.

To get your expected functionality, you could create a content control inside the tab UserControl, 

    <UserControl x:Class="MyTabControl"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             mc:Ignorable="d"
             d:DesignHeight="300"
             d:DesignWidth="300">
    <Grid>
           <ContentControl Source={Binding CurrentView}
    </Grid>
    </UserControl>

And then in your TabViewModel you need to have a collection of ViewModels for your views, plus your CurrentView mode.

Then you create a UserControl for your view itself, and define it like this
    
        <DataTemplate DataType="{x:Type MyView}">
            <MyViewControl/>
        </DataTemplate>

like done in the demo project.

**Comment by Revsol** [comment]
Sorry, i expressed this not very well. Of course, the collection of Views consists of ViewModels and not of Views. And i did it like in your example.

**Comment by sskodje** [comment]
I can't see why this should cause the null reference exceptions though, unless it's some weird race condition. I guess you just need to begin commenting out code until it starts working again.

**Comment by Revsol** [comment]
i could reproduce it in the Demo. If you close a tab that is currently shown, then it selects the next tab and there is tabItem.ParentTabControl null.

**Comment by sskodje** [comment]
Did you do any other changes to the source? Can you test with the nuget version?

**Comment by Revsol** [comment]
I found it. for Testing purposes i commented the ItemCollection_CollectionChanged in ViewModelExampleBase out. It seem if i don't call
```C#
ICollectionView view = CollectionViewSource.GetDefaultView(this.ItemCollection) as ICollectionView;
view.Refresh();
```
then the ParentTabControl is null.

**Comment by sskodje** [comment]
Interesting. It has to be a race condition where the act of refreshing the view keeps the items attached to the control, but without using the CollectionView the items gets detached before the code runs.

A null check should do the trick, i don't think it will have any negative side effects.

**Comment by Revsol** [comment]
Works like a charm ;)
