### ISSUE TITLE
AddButton don't work when Background is not set

### ISSUE THREAD

**Issue by Revsol** [sskodje/wpfchrometabs-mvvm#8]
if you don't set the Background, the AddTabButton didn't work. He is there but not clickable.

**Comment by sskodje** [comment]
Unfortunately the hit test doesn't work on controls without a background. Try setting the background to  Brushes.Transparent and it should work again.

**Comment by Revsol** [comment]
Currently it doesn't bother me, cause the Background is set by me. But it would be better when the background is set to Transparent as default.

**Comment by sskodje** [comment]
You are absolutely right, i had missed that in the default template. Thank you for pointing it out, i'll have it fixed in the next release.

**Comment by Revsol** [comment]
Great, thank you ;)

**Comment by sskodje** [comment]
This issue is fixed in version 1.2

**Comment by Revsol** [comment]
Works, thx ;)
